# mode
mode: inference # inference, fine-tune
evaluate_only: True # True, False
debug: False # True, False
results_debug: results_debug.csv # debug file

# data path
enwiki_path: data/enwiki
enwiki_mdr_path: data/wiki_id2doc.json
enwiki_bz2_path: data/enwiki-20171001-pages-meta-current-withlinks-abstracts/

metaqa_path: data/metaqa/questions_all_hops.txt
metaqa_1hop_train_path: data/metaqa/1-hop/vanilla/qa_train.txt
metaqa_2hop_train_path: data/metaqa/2-hop/vanilla/qa_train.txt
metaqa_3hop_train_path: data/metaqa/3-hop/vanilla/qa_train.txt
metaqa_1hop_dev_path: data/metaqa/1-hop/vanilla/qa_dev.txt
metaqa_2hop_dev_path: data/metaqa/2-hop/vanilla/qa_dev.txt
metaqa_3hop_dev_path: data/metaqa/3-hop/vanilla/qa_dev.txt

hotpotqa_train_path: data/hotpotqa/hotpot_train_v1.1.json
#hotpotqa_dev_path: data/hotpotqa/hotpot_dev_distractor_v1.json
#hotpotqa_dev_path: data/hotpotqa/sample_100_hotpot_dev_distractor_related.json
hotpotqa_dev_path: data/hotpotqa/sample_100_hotpot_dev_distractor_2.json
#hotpotqa_dev_path: data/hotpotqa/sample_1_hotpot_dev_distractor_new.json # for program logic test
#hotpotqa_dev_path: data/hotpotqa/sample_14_hotpot_dev_cgqa_CoT_annotation.json # for manual settings
hotpotqa_demo_path: data/hotpotqa/sample_02_hotpot_dev_cgqa_CoT_annotation_demo.json
hotpotqa_graph_demo_path: data/hotpotqa/graph_demo.json

2wikimultihopqa_train_path: data/2wikimultihop/train.json
#2wikimultihopqa_dev_path: data/2wikimultihop/dev.json
#2wikimultihopqa_dev_path: data/2wikimultihop/sample_500_2wikimultihop_dev.json
2wikimultihopqa_dev_path: data/2wikimultihop/sample_100_2wikimultihop_dev.json.bak2
#2wikimultihopqa_dev_path: data/2wikimultihop/sample_100_2wikimultihop_dev_2.json
#2wikimultihopqa_dev_path: data/2wikimultihop/sample_10_2wikimultihop_dev.json
#2wikimultihopqa_dev_path: data/2wikimultihop/sample_1_2wikimultihop_dev.json
2wikimultihopqa_demo_path: data/2wikimultihop/sample_02_2wikimultihop_dev_cgqa_CoT_annotation_demo.json
2wikimultihopqa_graph_demo_path: data/2wikimultihop/graph_demo.json
2wikimultihopqa_id_aliases_path: data/2wikimultihop/id_aliases.json

# retriever config
top_n: 7
max_doc_length: 512 # split by tokenizer
min_doc_length: 5 # split by space
max_doc_number: 5000000 # max no. of documents in a pickle

# T5 config and related settings
model_max_length: 6000

# bm25
bm25_tokenizer: google/flan-t5-xl
    # google/flan-t5-(small/base/large/xl/xxl)

# elasticsearch settings
elastic_host: 'localhost'
elastic_port: 9200
max_retries: 10
time_out: 30
retry_on_timeout: True
force: False

# multiprocess settings
n_pool_tokenize: 31
n_pool_bm25: 10
n_pool_tfidf: 31
n_pool_spacy: 31

# mdr settings
batch_size_mdr: 512

# openai key path
openai_org_id: openai_org_id
openai_key: openai_key
account: account1 # account1, account2
max_total_length: 4096 # chat-gpt-0301
max_generate_length: 300
max_graph_length: 512

# graph construction for t5
graph_batch_size: 32

# training/inference setting
gpu_no: [0]
dataset: 2wikimultihopqa #hotpotqa, 2wikimultihop
dataset_name: 2wikimultihopqa_dev # hotpotqa_dev, 2wikimultihopqa_dev
context: wikipedia
# retrieval
retriever: golden # bm25, faiss, faiss-mdr, tfidf, golden, manual
retrieval: single # mdr: multi, others: single, unknown: iter
# graph
graph_type: entity
    # manual-entity, direct-entity (only for kg2)
    # entity, multi_node (not implemented), empty, none
ner_model: openai # spacy, openai, manual-ner
relation: full # full, useful, related (not implemented), none
rel_model: openai
    # openai, google/flan-t5-(small/base/large/xl/xxl), golden, manual-rel
rel_shot: few-shot # few-shot, zero-shot when rel_model is not manual-rel
# inference
shot: few-shot # few-shot, zero-shot
cot: True # True, False
infer_model: openai
    # openai, google/flan-t5-(small/base/large/xl/xxl)
batch_size: 1
    # for t5 models
    # given max input length 512
    # dpr: 96 for 1xA6000 49GB, 320 for 2xA100 160GB
    # t5-small: inference: 1024
    # t5-base : inference: 1024
    # t5-large: inference: 256
    # t5-3b   : inference: 64
    # t5-11b  : inference: 8
results_dir: results/
results_file: results_kg2_2.csv
results_file_CoT: results_CoT_kg2_2.csv
results_hotpot_file: results_hotpot_kg2_2.json
results_2wikimultihop_file: results_2wikimultihop_kg2_2.json
save_memory: True
override: none
    # none, context_reader, context_index, all
    # fetched_results, fetched_entity, fetched_graph, preprocessed_tuple

# intermediate files name for reusing and saving time
intermediate_folder: temp/
# category: context_reader
enwiki_corpus_pickle: enwiki_corpus.pkl
enwiki_corpus_tokens_pickle: enwiki_corpus_tokens.pkl
# category: context_index
tfidf_model_path: wiki_2023_02-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz
tfidf_db_path: wiki_2023_02.db
tfidf_docids_path: wiki_2023_02_docids.pkl
context_dpr_embedding_bin: context_dpr_embedding.mdr.bin
context_mdr_embedding_bin: wiki_index.npy
context_mdr_id2doc_bin: wiki_id2doc.json
# category: fetching_results
context_qa_tuple_text_pickle: context_qa_tuple_text_2.pkl
context_entity_qa_tuple_text_pickle: context_entity_qa_tuple_text_2.pkl
context_graph_qa_tuple_text_pickle: context_graph_qa_tuple_text_kg2_2.pkl
tuple_ids_pickle: tuple_ids_kg2_3.pkl

